/**
 * Pricing catalog — all rates, costs and multipliers live here.
 *
 * Generated by the in-app catalog editor. Edit here or in the UI; commit this
 * file to make changes permanent. The pricing engine reads DEFAULT_CATALOG.
 */

export const CONSTANTS = {
  HARDWARE_PRICE_MULT: 1.42,
  LAB_UNIT_PRICE: 185,
  HAAS_MONTHS: 60,
  HAAS_MONTHLY_PRICE_MULT: 1.2,
  O365_PRICE_MULT: 1.2,
  DATTO_HW_PRICE_MULT: 1.25,
  DATTO_LIC_PRICE_MULT: 1.42,
  TARGET_GROSS_MARGIN: 0.7,
} as const;

export type HardwarePriceRule = "markup" | "lab";

export interface HardwareItem {
  key: string;
  label: string;
  cost: number;
  unit:
    | { base: "locations"; factor?: number }
    | { base: "devices"; factor?: number }
    | { base: "fixed"; value: number };
  priceRule: HardwarePriceRule;
}

export const HARDWARE: HardwareItem[] = [
  { key: "fw", label: "Firewall 5yr (Hardware)", cost: 2950.04, unit: { base: "locations" }, priceRule: "markup" },
  { key: "fwLog", label: "Firewall LOG 5yr (License)", cost: 746.17, unit: { base: "locations" }, priceRule: "markup" },
  { key: "fwLab", label: "Firewall Labor", cost: 68, unit: { base: "locations", factor: 8 }, priceRule: "lab" },
  { key: "sw", label: "Switch 48 port (Hardware)", cost: 1357.65, unit: { base: "locations" }, priceRule: "markup" },
  { key: "swLic", label: "Switch Warranty 5yr (License)", cost: 928.99, unit: { base: "locations" }, priceRule: "markup" },
  { key: "swLab", label: "Switch Labor", cost: 68, unit: { base: "locations", factor: 6 }, priceRule: "lab" },
  { key: "ap", label: "AP (Hardware)", cost: 502.8, unit: { base: "locations" }, priceRule: "markup" },
  { key: "apLic", label: "AP Warranty 5yr (License)", cost: 343.5, unit: { base: "locations" }, priceRule: "markup" },
  { key: "apLab", label: "AP Labor", cost: 68, unit: { base: "locations", factor: 4 }, priceRule: "lab" },
  { key: "pc", label: "Computer (Hardware)", cost: 1571.84, unit: { base: "devices" }, priceRule: "markup" },
  { key: "pcLic", label: "Computer Warrant 5yr (License)", cost: 123.79, unit: { base: "devices" }, priceRule: "markup" },
  { key: "pcLab", label: "Computer Labor", cost: 68, unit: { base: "devices", factor: 3 }, priceRule: "lab" },
];

export interface ToolItem {
  key: string;
  label: string;
  cost: number;
  unit: { base: "devices" } | { base: "users" } | { base: "fixed"; value: number };
}

export const TOOLS: ToolItem[] = [
  { key: "k365", label: "K365 Endpoint (RMM/EDR/AV/RC)", cost: 6.4, unit: { base: "devices" } },
  { key: "vpen", label: "vPen Seat", cost: 0.8, unit: { base: "devices" } },
  { key: "kaseya", label: "Kaseya User (Inky/SaaS Alert&Protect)", cost: 4.99, unit: { base: "users" } },
  { key: "archtitan", label: "ArchTitan Archive", cost: 3, unit: { base: "users" } },
  { key: "duo", label: "Duo Seat", cost: 2.7, unit: { base: "users" } },
  { key: "bsn", label: "BSN (Training/DarkWeb)", cost: 50, unit: { base: "fixed", value: 1 } },
  { key: "itg", label: "ITG/MyITProcess", cost: 64.5, unit: { base: "fixed", value: 1 } },
  { key: "vulscan", label: "Vulscan Client", cost: 10, unit: { base: "fixed", value: 1 } },
  { key: "netdetective", label: "NetworkDetective", cost: 22, unit: { base: "fixed", value: 1 } },
];

export interface LaborItem {
  label: string;
  hours: number | { base: "devices"; factor: number };
  rate: number;
  alreadyMonthly: boolean;
}

export interface LaborTier {
  key: "coManaged" | "remote" | "standardEnterprise";
  label: string;
  noTravel: LaborItem[];
  travel: LaborItem[];
}

export const LABOR: LaborTier[] = [
  {
    key: "coManaged",
    label: "Co-Managed",
    noTravel: [
    { label: "Co-Managed TAM (4x6)", hours: 24, rate: 37, alreadyMonthly: false },
    { label: "Co-Managed vCIO ((2x4)+(2x6))", hours: 20, rate: 80, alreadyMonthly: false },
    { label: "Co-Managed Support (POC 0.15)", hours: { base: "devices", factor: 0.15 }, rate: 37, alreadyMonthly: true },
    ],
    travel: [
    { label: "Co-Managed TAM (4x8)", hours: 32, rate: 37, alreadyMonthly: false },
    { label: "Co-Managed vCIO (4x7)", hours: 28, rate: 80, alreadyMonthly: false },
    { label: "Co-Managed Support (POC 0.15)", hours: { base: "devices", factor: 0.15 }, rate: 37, alreadyMonthly: true },
    ],
  },
  {
    key: "remote",
    label: "Remote",
    noTravel: [
    { label: "Remote TAM (1x8)", hours: 8, rate: 37, alreadyMonthly: false },
    { label: "Remote vCIO (4x4)", hours: 16, rate: 80, alreadyMonthly: false },
    { label: "Remote Support (0.3 RHEM)", hours: { base: "devices", factor: 0.3 }, rate: 37, alreadyMonthly: true },
    ],
    travel: [
    { label: "Remote TAM (1x12)", hours: 12, rate: 37, alreadyMonthly: false },
    { label: "Remote vCIO (4x4)", hours: 16, rate: 80, alreadyMonthly: false },
    { label: "Remote Support (0.3 RHEM)", hours: { base: "devices", factor: 0.3 }, rate: 37, alreadyMonthly: true },
    ],
  },
  {
    key: "standardEnterprise",
    label: "Standard / Enterprise",
    noTravel: [
    { label: "Std/Ent TAM (12x6)", hours: 72, rate: 37, alreadyMonthly: false },
    { label: "Std/Ent vCIO (4x6)", hours: 24, rate: 80, alreadyMonthly: false },
    { label: "Std/Ent Support (0.3 RHEM)", hours: { base: "devices", factor: 0.3 }, rate: 37, alreadyMonthly: true },
    ],
    travel: [
    { label: "Std/Ent TAM (12x9)", hours: 108, rate: 37, alreadyMonthly: false },
    { label: "Std/Ent vCIO (4x9)", hours: 36, rate: 80, alreadyMonthly: false },
    { label: "Std/Ent Support (0.3 RHEM)", hours: { base: "devices", factor: 0.3 }, rate: 37, alreadyMonthly: true },
    ],
  },
];

export interface DattoOption {
  key: string;
  label: string;
  licCost: number;
}

export const DATTO_OPTIONS: DattoOption[] = [
  { key: "none", label: "None", licCost: 0 },
  { key: "4t", label: "Datto 4TB (ICR)", licCost: 581.9 },
  { key: "6t", label: "Datto 6TB (ICR)", licCost: 823.9 },
  { key: "8t", label: "Datto 8TB (ICR)", licCost: 955.9 },
];

export const O365_SEAT_COST = 18;

export interface PlanDef {
  key: string;
  label: string;
  laborTier: LaborTier["key"];
  includeHaaS: boolean;
}

export const PLANS: PlanDef[] = [
  { key: "coManaged", label: "Co-Managed", laborTier: "coManaged", includeHaaS: false },
  { key: "remote", label: "Remote", laborTier: "remote", includeHaaS: false },
  { key: "standard", label: "Standard", laborTier: "standardEnterprise", includeHaaS: false },
  { key: "enterprise", label: "Enterprise (HaaS)", laborTier: "standardEnterprise", includeHaaS: true },
];

export interface Catalog {
  hardware: HardwareItem[];
  tools: ToolItem[];
  labor: LaborTier[];
}

export const DEFAULT_CATALOG: Catalog = {
  hardware: HARDWARE,
  tools: TOOLS,
  labor: LABOR,
};
